export const projectsData = [
  {
    id: "iparkings",
    title: "iParkings",
    shortDescription: "Sistema de gestión de parkings, auto-cobro y página web",
    fullDescription:
      "iParkings es una solución integral para la gestión de estacionamientos que optimiza la experiencia del usuario y la eficiencia operativa. Desarrollé un sistema de auto-cobro intuitivo y una interfaz de gestión robusta, mejorando significativamente la satisfacción del cliente y la eficacia del negocio. El proyecto implicó un desarrollo full-stack, creando de una interfaz de usuario atractiva y fácil de usar teniendo en cuenta los distintos tipos de usuarios que hacen uso de la plataforma a diario.",
    imageSrc: "/images/iparkings.jpg",
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "PHP",
      "MySQL",
      "UX/UI Design",
      "Responsive Design",
    ],
    liveLink: "https://pagoparking.com",
    type: "work",
  },
  {
    id: "tengokarga",
    title: "TengoKarga",
    shortDescription: "Plataforma logística con desarrollo full stack",
    fullDescription:
      "TengoKarga es una plataforma logística avanzada para la que realicé desarrollo full stack. Implementé nuevas características utilizando React con Redux y Sagas en el frontend, mientras mantenía y optimizaba los servicios backend. El proyecto implicó trabajar con metodologías ágiles, realizar pruebas exhaustivas y utilizar control de versiones con GitHub para asegurar un desarrollo eficiente y de alta calidad.",
    imageSrc: "/images/tengokarga.jpg",
    technologies: [
      "React",
      "Redux",
      "Sagas",
      "Node.js",
      "Express",
      "MongoDB",
      "Testing",
      "Git",
    ],
    liveLink: "https://www.tengokarga.com.uy",
    type: "work",
  },
  {
    id: "timb-arquitectura",
    title: "Timb Arquitectura",
    shortDescription: "Sitio web responsive para estudio de arquitectos",
    fullDescription:
      "Para Timb Arquitectura, desarrollé un sitio web responsive que destaca el trabajo y la visión del estudio. Utilizando WordPress como base, implementé personalizaciones avanzadas en CSS para lograr un diseño único que refleja la estética y filosofía del estudio. El proyecto requirió una atención meticulosa al detalle en el diseño y la implementación de funcionalidades específicas solicitadas por el cliente.",
    imageSrc: "/images/timb1.jpg",
    technologies: ["WordPress", "CSS", "Responsive Design", "UX/UI Design"],
    liveLink: "https://www.timb.com.uy",
  },
  {
    id: "digitax",
    title: "Digitax",
    shortDescription: "Aplicación para cálculo de impuestos y gestión fiscal",
    fullDescription:
      "Digitax es una aplicación innovadora diseñada para facilitar el cálculo de impuestos y la gestión fiscal para profesionales e independientes. Como parte del equipo de desarrollo, implementé la interfaz de usuario utilizando Next.js, garantizando una experiencia fluida y eficiente. El proyecto implicó la integración del frontend con un backend en MongoDB y apiClient, asegurando la coherencia y efectividad de la aplicación en el manejo de datos fiscales complejos.",
    imageSrc: "/images/digitax.png",
    technologies: [
      "Next.js",
      "React",
      "MongoDB",
      "API Integration",
      "UX/UI Design",
    ],
    liveLink: "https://www.digitax.uy",
    type: "project",
  },
  {
    id: "portfolio",
    title: "Portfolio Personal",
    shortDescription: "Sitio web personal para mostrar proyectos y habilidades",
    fullDescription:
      "Mi portfolio personal es un proyecto que destaca mis habilidades como desarrollador frontend y UX/UI designer. Desarrollado con Next.js y Tailwind CSS, el sitio presenta una interfaz moderna y responsiva que muestra mis proyectos, habilidades y experiencia de manera atractiva. Implementé animaciones personalizadas y optimicé el rendimiento para ofrecer una experiencia de usuario excepcional.",
    imageSrc: "/images/portfolio.jpg",
    technologies: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Responsive Design",
      "UX/UI Design",
      "SEO Optimization",
    ],
    githubLink: "https://github.com/forirodriguez",
    liveLink: "https://portfolio-alfonsorodriguez-20.vercel.app/",
    type: "project",
  },
  /* {
    id: "ecommerce",
    title: "Plataforma Ecommerce",
    shortDescription: "Tienda en línea completa con funcionalidades avanzadas",
    fullDescription:
      "Desarrollé una plataforma de comercio electrónico robusta y escalable, diseñada para ofrecer una experiencia de compra fluida y atractiva. Este proyecto full-stack incorpora las mejores prácticas en desarrollo web moderno y diseño UX/UI. En el frontend, utilicé React con Redux para gestionar el estado de la aplicación de manera eficiente, implementando una interfaz de usuario intuitiva y responsiva. El backend, construido con Node.js y Express, maneja operaciones críticas como procesamiento de pagos, gestión de inventario en tiempo real y autenticación segura de usuarios. La integración con una base de datos MySQL garantiza un almacenamiento y recuperación de datos eficiente. Características destacadas incluyen un carrito de compras persistente, sistema de reseñas de productos, panel de administración para gestión de productos y pedidos, y optimización para motores de búsqueda (SEO).",
    imageSrc: "/images/ecommerce.jpg",
    technologies: [
      "React",
      "Redux",
      "Node.js",
      "Express",
      "MySQL",
      "RESTful API",
      "Responsive Design",
      "UX/UI Design",
      "Payment Gateway Integration",
      "User Authentication",
      "SEO Optimization",
    ],
    githubLink: "https://github.com/forincho/ecommerce-platform",
    liveLink: "https://demo-ecommerce.alfonsorodriguez.dev",
  }, */
];
